version: "3.8"
services:
  db:
    image: mysql:8.0.27
    env_file:
      - variables.env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    volumes:
      - ./frontend/client:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
volumes:
  mysql_data: